import uuid
from datetime import datetime, timezone, date
from sqlalchemy import String, Text, Integer, Boolean, Date, DateTime, Index
from sqlalchemy.orm import Mapped, mapped_column
from app.core.database import Base

def generate_uuid() -> str:
    return str(uuid.uuid4())

def utc_now() -> datetime:
    return datetime.now(timezone.utc)

class ClinicalData(Base):
    __tablename__ = "clinical_data"
    
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    
    # PAGE 1: Case Overview
    patient_first_name: Mapped[str | None] = mapped_column(Text)
    patient_last_name: Mapped[str | None] = mapped_column(Text)
    patient_gender: Mapped[str | None] = mapped_column(String(10))
    patient_dob: Mapped[date | None] = mapped_column(Date)
    patient_address: Mapped[str | None] = mapped_column(Text)
    medical_history: Mapped[bool] = mapped_column(Boolean, default=False)
    medications: Mapped[bool] = mapped_column(Boolean, default=False)
    allergies: Mapped[bool] = mapped_column(Boolean, default=False)
    immunizations: Mapped[bool] = mapped_column(Boolean, default=False)
    past_medical_history: Mapped[bool] = mapped_column(Boolean, default=False)
    family_history: Mapped[bool] = mapped_column(Boolean, default=False)
    current_drug_regimens: Mapped[str | None] = mapped_column(Text)
    current_medications: Mapped[str | None] = mapped_column(Text)
    current_allergies: Mapped[str | None] = mapped_column(Text)
    current_immunizations: Mapped[str | None] = mapped_column(Text)
    
    # PAGE 2: Presenting Complaints
    complaints_description: Mapped[str | None] = mapped_column(Text)
    complaints_history: Mapped[str | None] = mapped_column(Text)
    history_of_presenting_complaints: Mapped[str | None] = mapped_column(Text)
    
    # PAGE 3: Allergies & Family History
    allergy_years: Mapped[str | None] = mapped_column(String(100))
    allergy_treatment: Mapped[str | None] = mapped_column(Text)
    allergy_product_used: Mapped[str | None] = mapped_column(Text)
    allergy_current: Mapped[bool] = mapped_column(Boolean, default=False)
    allergy_reason: Mapped[str | None] = mapped_column(Text)
    family_birthdate: Mapped[date | None] = mapped_column(Date)
    family_mother: Mapped[str | None] = mapped_column(Text)
    family_father: Mapped[str | None] = mapped_column(Text)
    family_mother_male: Mapped[str | None] = mapped_column(Text)
    family_male_other: Mapped[str | None] = mapped_column(Text)
    family_sex_of: Mapped[str | None] = mapped_column(String(100))
    family_sex_of_2: Mapped[str | None] = mapped_column(String(100))
    
    # PAGE 4: Aggravation & Amelioration + Mental Trail
    emotional_family: Mapped[str | None] = mapped_column(Text)
    emotional_authority: Mapped[str | None] = mapped_column(Text)
    physical_leadership: Mapped[str | None] = mapped_column(Text)
    physical_setting: Mapped[str | None] = mapped_column(Text)
    motivational_upbringing: Mapped[str | None] = mapped_column(Text)
    motivational_acquiring_1: Mapped[str | None] = mapped_column(Text)
    motivational_acquiring_2: Mapped[str | None] = mapped_column(Text)
    future_responsibility: Mapped[str | None] = mapped_column(Text)
    future_meaning: Mapped[str | None] = mapped_column(Text)
    future_decision: Mapped[str | None] = mapped_column(Text)
    future_creation: Mapped[str | None] = mapped_column(Text)
    future_order: Mapped[str | None] = mapped_column(Text)
    future_stress: Mapped[str | None] = mapped_column(Text)
    future_time: Mapped[str | None] = mapped_column(Text)
    future_create: Mapped[str | None] = mapped_column(Text)
    future_destiny: Mapped[str | None] = mapped_column(Text)
    positive_reinforcement: Mapped[str | None] = mapped_column(Text)
    motivation: Mapped[str | None] = mapped_column(Text)
    stress_on_task_performance: Mapped[str | None] = mapped_column(Text)
    time_management: Mapped[str | None] = mapped_column(Text)
    success_and_promotion: Mapped[str | None] = mapped_column(Text)
    job_name_1: Mapped[str | None] = mapped_column(Text)
    job_name_2: Mapped[str | None] = mapped_column(Text)
    job_position_1: Mapped[str | None] = mapped_column(Text)
    job_position_2: Mapped[str | None] = mapped_column(Text)
    job_position_3: Mapped[str | None] = mapped_column(Text)
    job_position_4: Mapped[str | None] = mapped_column(Text)
    activity_name: Mapped[str | None] = mapped_column(Text)
    activity_position: Mapped[str | None] = mapped_column(Text)
    ev_event: Mapped[str | None] = mapped_column(Text)
    ev_time: Mapped[str | None] = mapped_column(String(100))
    ev_position_1: Mapped[str | None] = mapped_column(Text)
    ev_position_2: Mapped[str | None] = mapped_column(Text)
    ev_position_3: Mapped[str | None] = mapped_column(Text)
    ev_position_4: Mapped[str | None] = mapped_column(Text)
    
    # PAGE 5: Personal History
    personal_history_details: Mapped[str | None] = mapped_column(Text)
    identified_causations: Mapped[str | None] = mapped_column(Text)
    disease_name: Mapped[str | None] = mapped_column(Text)
    treatment_history: Mapped[str | None] = mapped_column(Text)
    treatment_method: Mapped[str | None] = mapped_column(Text)
    treatment_result: Mapped[str | None] = mapped_column(Text)
    result: Mapped[str | None] = mapped_column(Text)
    sides_parietal: Mapped[str | None] = mapped_column(Text)
    vertex: Mapped[str | None] = mapped_column(Text)
    sensation: Mapped[str | None] = mapped_column(Text)
    sleep_pattern: Mapped[str | None] = mapped_column(Text)
    bathing: Mapped[str | None] = mapped_column(Text)
    head_injury: Mapped[str | None] = mapped_column(Text)
    head_skin: Mapped[str | None] = mapped_column(Text)
    concomitants: Mapped[str | None] = mapped_column(Text)
    modality: Mapped[str | None] = mapped_column(Text)
    forehead: Mapped[str | None] = mapped_column(Text)
    perspiration: Mapped[str | None] = mapped_column(Text)
    alcoholic: Mapped[str | None] = mapped_column(Text)
    movement: Mapped[str | None] = mapped_column(Text)
    endocrin: Mapped[str | None] = mapped_column(Text)
    temple: Mapped[str | None] = mapped_column(Text)
    vertigo: Mapped[str | None] = mapped_column(Text)
    time_of_vertigo: Mapped[str | None] = mapped_column(Text)
    vomiting: Mapped[str | None] = mapped_column(Text)
    dropsical: Mapped[str | None] = mapped_column(Text)
    
    # PAGE 6: Obstetrical & General Clinical
    cycle_regularity: Mapped[str | None] = mapped_column(String(50))
    cycle_days: Mapped[int] = mapped_column(Integer, default=28)
    duration_days: Mapped[int] = mapped_column(Integer, default=5)
    flow: Mapped[str | None] = mapped_column(String(50))
    general_serial_history: Mapped[str | None] = mapped_column(Text)
    marriage_notes: Mapped[str | None] = mapped_column(Text)
    pregnancy_notes: Mapped[str | None] = mapped_column(Text)
    gravida: Mapped[int | None] = mapped_column(Integer)
    para: Mapped[int | None] = mapped_column(Integer)
    abortions: Mapped[int | None] = mapped_column(Integer)
    obstetrical_complications: Mapped[str | None] = mapped_column(Text)
    maternal_history: Mapped[str | None] = mapped_column(Text)
    paternal_history: Mapped[str | None] = mapped_column(Text)
    sisters_history: Mapped[str | None] = mapped_column(Text)
    brothers_history: Mapped[str | None] = mapped_column(Text)
    mothers_on: Mapped[str | None] = mapped_column(Text)
    husbands_partner: Mapped[str | None] = mapped_column(Text)
    excreta_quantity: Mapped[str | None] = mapped_column(String(100))
    excreta_colour: Mapped[str | None] = mapped_column(String(100))
    excreta_consumption: Mapped[str | None] = mapped_column(Text)
    excreta_cloths: Mapped[str | None] = mapped_column(Text)
    excreta_odor: Mapped[str | None] = mapped_column(String(100))
    excreta_stain: Mapped[str | None] = mapped_column(String(100))
    excreta_pain: Mapped[str | None] = mapped_column(String(100))
    fever: Mapped[str | None] = mapped_column(Text)
    chill: Mapped[str | None] = mapped_column(Text)
    sweat: Mapped[str | None] = mapped_column(Text)
    time_onset: Mapped[str | None] = mapped_column(String(100))
    befores: Mapped[str | None] = mapped_column(Text)
    duration: Mapped[str | None] = mapped_column(String(100))
    past_history: Mapped[str | None] = mapped_column(Text)
    personality_type: Mapped[str | None] = mapped_column(String(100))
    concomitant: Mapped[str | None] = mapped_column(Text)
    drugs: Mapped[str | None] = mapped_column(Text)
    
    # PAGE 7: Social, Psychological & Mental
    aunt: Mapped[str | None] = mapped_column(Text)
    uncle: Mapped[str | None] = mapped_column(Text)
    daughter: Mapped[str | None] = mapped_column(Text)
    wife: Mapped[str | None] = mapped_column(Text)
    son: Mapped[str | None] = mapped_column(Text)
    living_status: Mapped[str | None] = mapped_column(Text)
    deceased: Mapped[str | None] = mapped_column(Text)
    tea: Mapped[str | None] = mapped_column(String(100))
    coffee: Mapped[str | None] = mapped_column(String(100))
    alcohol: Mapped[str | None] = mapped_column(String(100))
    beer: Mapped[str | None] = mapped_column(String(100))
    tobacco: Mapped[str | None] = mapped_column(String(100))
    chewing: Mapped[str | None] = mapped_column(String(100))
    parental_attitude: Mapped[str | None] = mapped_column(Text)
    society: Mapped[str | None] = mapped_column(Text)
    work_place: Mapped[str | None] = mapped_column(Text)
    family_dynamic: Mapped[str | None] = mapped_column(Text)
    dissatisfaction: Mapped[str | None] = mapped_column(Text)
    strain: Mapped[str | None] = mapped_column(Text)
    love: Mapped[str | None] = mapped_column(Text)
    hate: Mapped[str | None] = mapped_column(Text)
    attachment: Mapped[str | None] = mapped_column(Text)
    anger: Mapped[str | None] = mapped_column(Text)
    sadness: Mapped[str | None] = mapped_column(Text)
    anxiety: Mapped[str | None] = mapped_column(Text)
    ego: Mapped[str | None] = mapped_column(Text)
    jealous: Mapped[str | None] = mapped_column(Text)
    suspicious: Mapped[str | None] = mapped_column(Text)
    envy: Mapped[str | None] = mapped_column(Text)
    memory_state: Mapped[str | None] = mapped_column(Text)
    mental_characteristics: Mapped[str | None] = mapped_column(Text)
    activity_levels: Mapped[str | None] = mapped_column(Text)
    general_behavior: Mapped[str | None] = mapped_column(Text)
    
    # Audit fields
    created_by: Mapped[str | None] = mapped_column(String(36))
    updated_by: Mapped[str | None] = mapped_column(String(36))
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utc_now)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=utc_now, onupdate=utc_now)


